apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-api
  description: Dummy Pet Store API for demo
spec:
  type: openapi
  lifecycle: experimental
  owner: team-demo
  definition:
    $url: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml
