apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-service
  description: A dummy service to demo Backstage catalog features.
  tags:
    - demo
    - example
  annotations:
    github.com/project-slug: ank112/backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: team-demo

