apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
  description: A dummy REST API for demonstration purposes.
  tags:
    - demo
    - rest
spec:
  type: openapi
  lifecycle: experimental
  owner: team-demo
  definition:
    $text: |
      openapi: 3.0.0
      info:
        title: Demo API
        version: 1.0.0
      paths:
        /hello:
          get:
            summary: Returns a greeting
            responses:
              '200':
                description: A successful response
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        message:
                          type: string
